services:
  postgres:
    image: postgres:13.8-alpine
    container_name: chats-db
    environment:
      - POSTGRES_DB=chats-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 6432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 1s
      retries: 30